# Generated by Django 6.0.7 on 2026-08-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sunamoebi', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
