# Generated by Django 6.0.7 on 2026-08-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sunamoebi', '0003_category_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
